# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c4692df9e45bf71d7ee8bb2d9af8511284b09ed03440d7732495620f07665a4f7c2424f4f8d3e66785581f5969b82d8077e5a32ed46ceff0469412d9f11e1da

test:
  secret_key_base: 4577746ea4f55d7e09f8076c53170a28a571349bd47da65b2e4adc21bcc14e6423eb0a0f7c96c04b806e1cfb4b4aa91869585869c6cfbf149c9879676aa24185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
